# Generated by Django 4.2.4 on 2023-08-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_users',
            new_name='User',
        ),
    ]
