from datetime import datetime
from django.test import TestCase
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
scroll_amount = 500

class Hosttest(TestCase):
    
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)
        self.live_server_url = 'http://127.0.0.1:8000/'

    def tearDown(self):
        self.driver.quit()
        
    def test_01_login_page(self):
        driver = self.driver
        driver.get(self.live_server_url)
        driver.maximize_window()
        
        # #Test 1
        # login=driver.find_element(By.CSS_SELECTOR,"a.nav-link[href='/login/'] button.btn.btn-outline-success")
        # login.click()
        # time.sleep(2)
        # email=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='email']")
        # email.send_keys("rojin@gmail.com")
        # password=driver.find_element(By.CSS_SELECTOR,"input[type='password'][name='password']")
        # password.send_keys("Rojin@123")
        # time.sleep(2)
        # submit=driver.find_element(By.CSS_SELECTOR,"button.btn-login#submitBtn")
        # submit.click()
        # time.sleep(2)
        
        
        # #Test 2
        # postadd=driver.find_element(By.CSS_SELECTOR,"#v-pills-approved-tab")
        # postadd.click()
        # time.sleep(3)
        # pname=driver.find_element(By.CSS_SELECTOR,"input#pname[type='text'][name='pname'][required]")
        # pname.send_keys("Saab Villas")
        # time.sleep(2)
        # paddress=driver.find_element(By.CSS_SELECTOR,"textarea#address[name='address'][rows='4'][placeholder='Do not include state and country'][required]")
        # paddress.send_keys("North left street, Manhattan")
        # time.sleep(2)
        # mlink=driver.find_element(By.CSS_SELECTOR,"input#mlink[type='text'][name='mlink'][required]")
        # mlink.send_keys("https://maps.app.goo.gl/niugDm8GaZaQ4qSd7")
        # time.sleep(2)
        # nation=driver.find_element(By.CSS_SELECTOR,"select#nation")
        # nation.click()
        # nationselect=driver.find_element(By.CSS_SELECTOR,"option[value='Ireland']")
        # nationselect.click()
        # time.sleep(1)
        # state=driver.find_element(By.CSS_SELECTOR,"select#region")
        # state.click()
        # stateselect=driver.find_element(By.CSS_SELECTOR,"option[value='Connacht']")
        # stateselect.click()
        # time.sleep(1)
        # city=driver.find_element(By.CSS_SELECTOR,"select#city")
        # city.click()
        # cityselect=driver.find_element(By.CSS_SELECTOR,"option[value='Galway']")
        # cityselect.click()
        # time.sleep(2)
        # file_path = 'C:\\Users\\Rony\\Downloads\\frontview17.jpg'
        # img1 = driver.find_element(By.CSS_SELECTOR, "input#frontview[type='file']")
        # img1.send_keys(file_path)
        # time.sleep(2)
        # file_path = 'C:\\Users\\Rony\\Downloads\\living11.jpg'
        # img1 = driver.find_element(By.CSS_SELECTOR, "input#living[type='file']")
        # img1.send_keys(file_path)
        # time.sleep(5)
        # file_path = 'C:\\Users\\Rony\\Downloads\\bedroom13.jpg'
        # img1 = driver.find_element(By.CSS_SELECTOR, "input#bedroom[type='file']")
        # img1.send_keys(file_path)
        # time.sleep(2)
        # file_path = 'C:\\Users\\Rony\\Downloads\\bathroom.jpg'
        # img1 = driver.find_element(By.CSS_SELECTOR, "input#bathroom[type='file']")
        # img1.send_keys(file_path)
        # time.sleep(2)
        # file_path = 'C:\\Users\\Rony\\Downloads\\kitchen12.png'
        # img1 = driver.find_element(By.CSS_SELECTOR, "input#kitchen[type='file']")
        # img1.send_keys(file_path)
        # time.sleep(2)
        # file_path = 'C:\\Users\\Rony\\Downloads\\dining14.jpeg'
        # img1 = driver.find_element(By.CSS_SELECTOR, "input#dining[type='file']")
        # img1.send_keys(file_path)
        # time.sleep(2)
        # file_path = 'C:\\Users\\Rony\\Downloads\\garage16.jpg'
        # img1 = driver.find_element(By.CSS_SELECTOR, "input#other1[type='file']")
        # img1.send_keys(file_path)
        # time.sleep(2)
        # file_path = 'C:\\Users\\Rony\\Downloads\\backyard.jpg'
        # img1 = driver.find_element(By.CSS_SELECTOR, "input#other2[type='file']")
        # img1.send_keys(file_path)
        # time.sleep(2)
        # duration=driver.find_element(By.CSS_SELECTOR,"select#duration")
        # duration.click()
        # durationselect=driver.find_element(By.CSS_SELECTOR,"option[value='2']")
        # durationselect.click()
        # time.sleep(2)
        # bhk=driver.find_element(By.CSS_SELECTOR,"select#bhk")
        # bhk.click()
        # bhkselect=driver.find_element(By.CSS_SELECTOR,"option[value='2']")
        # bhkselect.click()
        # time.sleep(2)
        # sqft=driver.find_element(By.CSS_SELECTOR,"input#sqft")
        # sqft.send_keys("800")
        # time.sleep(2)
        # bth=driver.find_element(By.CSS_SELECTOR,"select#bth")
        # bth.click()
        # bthselect=driver.find_element(By.CSS_SELECTOR,"option[value='2']")
        # bthselect.click()
        # time.sleep(2)
        # contact=driver.find_element(By.CSS_SELECTOR,"input#contact")
        # contact.send_keys("+19873625473")
        # time.sleep(2)
        # rent=driver.find_element(By.CSS_SELECTOR,"input#rent")
        # rent.send_keys("350")
        # time.sleep(2)
        # parea=driver.find_element(By.CSS_SELECTOR,"input#Parea")
        # parea.click()
        # time.sleep(2)
        # pback=driver.find_element(By.CSS_SELECTOR,"input#pback")
        # pback.click()
        # time.sleep(2)
        # submit=driver.find_element(By.CSS_SELECTOR,"button#submitBtn[type='submit']")
        # submit.click()
        # time.sleep(3)
        # print("Ad posted successfully")
        # pendingad=driver.find_element(By.CSS_SELECTOR,"#v-pills-pending-tab")
        # pendingad.click()
        # time.sleep(2)
        # logoutname=driver.find_element(By.CSS_SELECTOR,"a.nav-link.text-success[role='button']")
        # logoutname.click()
        # time.sleep(2)
        # logout=driver.find_element(By.CSS_SELECTOR,"a.dropdown-item[href='/logout/']")
        # logout.click()
        # time.sleep(5)
        
        
        # #Test 3
        # login=driver.find_element(By.CSS_SELECTOR,"a.nav-link[href='/login/'] button.btn.btn-outline-success")
        # login.click()
        # time.sleep(2)
        # email=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='email']")
        # email.send_keys("ontario@gmail.com")
        # password=driver.find_element(By.CSS_SELECTOR,"input[type='password'][name='password']")
        # password.send_keys("Ontario@123")
        # time.sleep(2)
        # submit=driver.find_element(By.CSS_SELECTOR,"button.btn-login#submitBtn")
        # submit.click()
        # time.sleep(3)
        # addcourse=driver.find_element(By.CSS_SELECTOR,"a.nav-link[href='/addcourse/']")
        # addcourse.click()
        # time.sleep(2)
        # coursecode=driver.find_element(By.CSS_SELECTOR,"input#course_code")
        # coursecode.send_keys("ONTMSCC109")
        # time.sleep(1)
        # coursename=driver.find_element(By.CSS_SELECTOR,"input#course_name")
        # coursename.send_keys("MS in computer Application")
        # time.sleep(1)
        # coursemode=driver.find_element(By.CSS_SELECTOR,"select#course_mode")
        # coursemode.click()
        # coursemodeselect=driver.find_element(By.CSS_SELECTOR,"option[value='On-campus']")
        # coursemodeselect.click()
        # time.sleep(1)
        # coursetype=driver.find_element(By.CSS_SELECTOR,"select#course_type")
        # coursetype.click()
        # coursetypeselect=driver.find_element(By.CSS_SELECTOR,"option[value='Master Degree']")
        # coursetypeselect.click()
        # time.sleep(1)
        # coursetype=driver.find_element(By.CSS_SELECTOR,"select#academic_disciplines")
        # coursetype.click()
        # coursetypeselect=driver.find_element(By.CSS_SELECTOR,"option[value='Engineering and Applied Science']")
        # coursetypeselect.click()
        # time.sleep(1)
        # desc=driver.find_element(By.CSS_SELECTOR,"textarea#course_desc")
        # desc.send_keys("This is a test course desc")
        # time.sleep(1)
        # eligibility=driver.find_element(By.CSS_SELECTOR,"textarea#eligibility")
        # eligibility.send_keys("This is a test course eligibility")
        # time.sleep(1)
        # fees=driver.find_element(By.CSS_SELECTOR,"input#fees[type='number']")
        # fees.send_keys("210")
        # time.sleep(1)
        # coursedur=driver.find_element(By.CSS_SELECTOR,"select#duration")
        # coursedur.click()
        # time.sleep(1)
        # coursedurselect=driver.find_element(By.CSS_SELECTOR,"select#duration option[value='2 years']")
        # coursedurselect.click()
        # time.sleep(1)
        # input_date1= "2024-04-20"
        # formatted_date = datetime.strptime(input_date1, '%Y-%m-%d').strftime('%m-%d-%Y')
        # opendate_input = driver.find_element(By.CSS_SELECTOR, "input#opendate")
        # opendate_input.send_keys(formatted_date)
        # time.sleep(1)
        # input_date2= "2024-05-28"
        # formatted_date = datetime.strptime(input_date2, '%Y-%m-%d').strftime('%m-%d-%Y')
        # deaddate_input = driver.find_element(By.CSS_SELECTOR, "input#appdeadline")
        # deaddate_input.send_keys(formatted_date)
        # time.sleep(1)
        # file_path = 'C:\\Users\\Rony\\Downloads\\IT.jpeg'
        # thumbnail_image_input = driver.find_element(By.CSS_SELECTOR, "input#thumbnail_image[type='file']")
        # thumbnail_image_input.send_keys(file_path)
        # time.sleep(3)
        # seats_available_input = driver.find_element(By.CSS_SELECTOR, "input#seats_available")
        # seats_available_input.send_keys("20")
        # time.sleep(1)
        # submit_button = driver.find_element(By.CSS_SELECTOR, "input[type='submit'].btn.btn-primary#submitBtn")
        # submit_button.click()
        # time.sleep(5)       
        # print("Added course successfully")
        # logoutname=driver.find_element(By.CSS_SELECTOR,"a.nav-link.text-success[role='button']")
        # logoutname.click()
        # time.sleep(2)
        # logout=driver.find_element(By.CSS_SELECTOR,"a.dropdown-item[href='/logout/']")
        # logout.click()
        # time.sleep(5)
        
    
        # #Test 4
        # login=driver.find_element(By.CSS_SELECTOR,"a.nav-link[href='/login/'] button.btn.btn-outline-success")
        # login.click()
        # time.sleep(2)
        # email=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='email']")
        # email.send_keys("romeo@gmail.com")
        # password=driver.find_element(By.CSS_SELECTOR,"input[type='password'][name='password']")
        # password.send_keys("Romeo@123")
        # time.sleep(2)
        # submit=driver.find_element(By.CSS_SELECTOR,"button.btn-login#submitBtn")
        # submit.click()
        # time.sleep(2)
        # adlisting = driver.find_element(By.CSS_SELECTOR, "a.show-ads-listing-btn")
        # adlisting.click()
        # time.sleep(2)
        # reject = driver.find_element(By.ID, "rejectButton")
        # reject.click()
        # time.sleep(2)
        # remark = driver.find_element(By.ID, "rejectadRemarks")
        # remark.send_keys("Bad property image")

        # submit = driver.find_element(By.ID, "rejectPropertyButton")
        # submit.click()
        # adlisting = driver.find_element(By.CSS_SELECTOR, "a.show-ads-listing-btn")
        # adlisting.click()
        # time.sleep(2)
        # logoutname=driver.find_element(By.CSS_SELECTOR,"button.nav-user-btn.dropdown-btn[title='My profile']")
        # logoutname.click()
        # time.sleep(2)
        # logout=driver.find_element(By.CSS_SELECTOR,"a.danger[href='/logout/']")
        # logout.click()
        # time.sleep(5)
        
        
        
        # #Test 5
        login=driver.find_element(By.CSS_SELECTOR,"a.nav-link[href='/login/'] button.btn.btn-outline-success")
        login.click()
        time.sleep(2)
        email=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='email']")
        email.send_keys("ronybinoy189@gmail.com")
        password=driver.find_element(By.CSS_SELECTOR,"input[type='password'][name='password']")
        password.send_keys("Rony@123")
        time.sleep(2)
        submit=driver.find_element(By.CSS_SELECTOR,"button.btn-login#submitBtn")
        submit.click()
        print("login Successfull")
        time.sleep(3)
        
        # rentals=driver.find_element(By.CSS_SELECTOR,"a.nav-link[href='/acc_userview/']")
        # rentals.click()
        # time.sleep(3)
        # search=driver.find_element(By.CSS_SELECTOR,"a.btn.btn-primary[href='/acc_listproperty/']")
        # search.click()
        # time.sleep(2)
        # driver.execute_script(f"window.scrollBy(0, {scroll_amount});")
        # time.sleep(1)
        # search=driver.find_element(By.CSS_SELECTOR," button.btn.btn-primary[type='submit']")
        # search.click()
        # time.sleep(2)
        # driver.execute_script(f"window.scrollBy(0, {scroll_amount});")
        # time.sleep(1)
        # search=driver.find_element(By.CSS_SELECTOR," a#book.btn.btn-primary")
        # search.click()
        # time.sleep(3)
        # driver.execute_script(f"window.scrollBy(0, 200);")
        # selfspan=driver.find_element(By.CSS_SELECTOR," span#selfSpan.clickable")
        # selfspan.click()
        # time.sleep(2)
        # selfspan=driver.find_element(By.CSS_SELECTOR," span#otherSpan.clickable")
        # selfspan.click()
        # time.sleep(2)
        # selfspan=driver.find_element(By.CSS_SELECTOR," span#selfSpan.clickable")
        # selfspan.click()
        # time.sleep(2)
        # contact=driver.find_element(By.CSS_SELECTOR,"input#contact")
        # contact.send_keys("9846242069")
        # time.sleep(2)
        # address=driver.find_element(By.CSS_SELECTOR,"input#address")
        # address.send_keys("Amal Jyothi College of Engineering, Kanjirapally")
        # time.sleep(2)
        # country=driver.find_element(By.CSS_SELECTOR,"select#country")
        # country.click()
        # countryselect=driver.find_element(By.CSS_SELECTOR,"option[value='India']")
        # countryselect.click()
        # time.sleep(2)
        # state=driver.find_element(By.CSS_SELECTOR,"input#state")
        # state.send_keys("Kerala")
        # time.sleep(2)
        # passportNumber=driver.find_element(By.CSS_SELECTOR,"input#passportNumber")
        # passportNumber.send_keys("34535345")
        # time.sleep(2)
        # file_path = 'E:\\Project\\unwanted\\passport.pdf'
        # thumbnail_image_input = driver.find_element(By.CSS_SELECTOR, "input#passportUpload")
        # thumbnail_image_input.send_keys(file_path)
        # time.sleep(2)
        # input_date1= "2024-04-12"
        # formatted_date = datetime.strptime(input_date1, '%Y-%m-%d').strftime('%m-%d-%Y')
        # opendate_input = driver.find_element(By.CSS_SELECTOR, "input#checkin")
        # opendate_input.send_keys(formatted_date)
        # time.sleep(2)
        # adultcount=driver.find_element(By.CSS_SELECTOR,"input#adultcount")
        # adultcount.send_keys("2")
        # time.sleep(2)
        # req=driver.find_element(By.ID,"request")
        # req.send_keys("Nil")
        # time.sleep(2)
        # ename=driver.find_element(By.ID,"emergency")
        # ename.send_keys("Kevin Richard")
        # time.sleep(2)
        # rel=driver.find_element(By.CSS_SELECTOR,"select#emerrel")
        # rel.click()
        # relselect=driver.find_element(By.CSS_SELECTOR,"option[value='Brother']")
        # relselect.click()
        # time.sleep(2)
        # emercon=driver.find_element(By.ID,"emercon")
        # emercon.send_keys("4343535336")
        # time.sleep(2)
        # agree=driver.find_element(By.CSS_SELECTOR,"input#agreement")
        # agree.click()
        # submit=driver.find_element(By.CSS_SELECTOR,"button#submitBtn")
        # submit.click()
        # time.sleep(3)
        # paybtn=driver.find_element(By.CSS_SELECTOR,"button#pay-btn")
        # paybtn.click()
        # time.sleep(3)
        
if __name__ == '__main__':
    import unittest
    unittest.main()
    
    
        #     email=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='email']")
        #     email.send_keys("ronybinoy189@gmail.com")
        #     password=driver.find_element(By.CSS_SELECTOR,"input[type='password'][name='password']")
        #     password.send_keys("Rony@123")
        #     time.sleep(2)
        #     submit=driver.find_element(By.CSS_SELECTOR,"button.btn-login#submitBtn")
        #     submit.click()
        #     time.sleep(2)
        #     chatroom=driver.find_element(By.CSS_SELECTOR,"a.nav-link[href='/chatroom']")
        #     chatroom.click()
        #     time.sleep(2)
        #     chatstart=driver.find_element(By.CSS_SELECTOR,"a.btn.btn-primary[href='/rooms']")
        #     chatstart.click()
        #     time.sleep(2)
        #     room=driver.find_element(By.CSS_SELECTOR,"a.bg-primary[href='/canada/']")
        #     room.click()
        #     time.sleep(2)
        #     roomtext=driver.find_element(By.CSS_SELECTOR,"input[name='content']#chat-message-input")
        #     roomtext.send_keys("hello this is a test message")
        #     time.sleep(2)
        #     send=driver.find_element(By.CSS_SELECTOR,"button#chat-message-submit")
        #     send.click()
        #     time.sleep(2)
        #     roomsearch=driver.find_element(By.CSS_SELECTOR,"input#search-input")
        #     roomsearch.send_keys("hello")
        #     time.sleep(2)
        #     search=driver.find_element(By.CSS_SELECTOR,"button#search-button")
        #     search.click()
        #     time.sleep(2)
        #     more=driver.find_element(By.CSS_SELECTOR,"button#next-button.btn.btn-outline-secondary")
        #     more.click()
        #     time.sleep(2)
        #     more.click()
        #     time.sleep(2)
        #     roomsearch=driver.find_element(By.CSS_SELECTOR,"input#search-input")
        #     roomsearch.send_keys("text not in chat")
        #     time.sleep(2)
        #     search1=driver.find_element(By.CSS_SELECTOR,"button#search-button")
        #     search1.click()
        #     time.sleep(2)
        #     modalclose=driver.find_element(By.CSS_SELECTOR,"button.btn.bg-primary.text-white[data-dismiss='modal']")
        #     modalclose.click()
        #     time.sleep(2)
        #     roomclose=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-danger#close-chat-room")
        #     roomclose.click()
        #     time.sleep(2)
        #     roomclose=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-danger#close-chat-room")
        #     roomclose.click()
        #     time.sleep(2)
        #     profile=driver.find_element(By.CSS_SELECTOR,"a.nav-link.text-success p")
        #     profile.click()
        #     time.sleep(2)
        #     logout = driver.find_element(By.CSS_SELECTOR, "a.dropdown-item[href='/logout/']")
        #     logout.click()
        #     time.sleep(2)
        #     login=driver.find_element(By.CSS_SELECTOR,"a.nav-link[href='/login/'] button.btn.btn-outline-success")
        #     login.click()
        #     time.sleep(2)
        #     email=driver.find_element(By.CSS_SELECTOR,"input[type='email'][name='email']")
        #     email.send_keys("ontario@gmail.com")
        #     password=driver.find_element(By.CSS_SELECTOR,"input[type='password'][name='password']")
        #     password.send_keys("Ontario@123")
        #     time.sleep(2)
        #     submit=driver.find_element(By.CSS_SELECTOR,"button.btn-login#submitBtn")
        #     submit.click()
        #     time.sleep(3)
        #     addcourse=driver.find_element(By.CSS_SELECTOR,"button.btn.btn-primary#learnMoreButton")
        #     addcourse.click()
        #     time.sleep(2)
        #     coursename=driver.find_element(By.CSS_SELECTOR,"input#course_name")
        #     coursename.send_keys("MS in computer Application")
        #     time.sleep(1)
        #     coursemode=driver.find_element(By.CSS_SELECTOR,"select#course_mode")
        #     coursemode.click()
        #     coursemodeselect=driver.find_element(By.CSS_SELECTOR,"option[value='On-campus']")
        #     coursemodeselect.click()
        #     time.sleep(1)
        #     coursetype=driver.find_element(By.CSS_SELECTOR,"select#course_type")
        #     coursetype.click()
        #     coursetypeselect=driver.find_element(By.CSS_SELECTOR,"option[value='Master Degree']")
        #     coursetypeselect.click()
        #     time.sleep(1)
        #     coursetype=driver.find_element(By.CSS_SELECTOR,"select#academic_disciplines")
        #     coursetype.click()
        #     coursetypeselect=driver.find_element(By.CSS_SELECTOR,"option[value='Engineering and Applied Science']")
        #     coursetypeselect.click()
        #     time.sleep(1)
        #     desc=driver.find_element(By.CSS_SELECTOR,"textarea#course_desc")
        #     desc.send_keys("This is a test course desc")
        #     time.sleep(1)
        #     eligibility=driver.find_element(By.CSS_SELECTOR,"textarea#eligibility")
        #     eligibility.send_keys("This is a test course eligibility")
        #     time.sleep(1)
        #     fees=driver.find_element(By.CSS_SELECTOR,"input#fees[type='number']")
        #     fees.send_keys("210")
        #     time.sleep(1)
        #     coursedur=driver.find_element(By.CSS_SELECTOR,"select#duration")
        #     coursedur.click()
        #     time.sleep(1)
        #     coursedurselect=driver.find_element(By.CSS_SELECTOR,"select#duration option[value='2 years']")
        #     coursedurselect.click()
        #     time.sleep(1)
        #     input_date1= "2023-10-20"
        #     formatted_date = datetime.strptime(input_date1, '%Y-%m-%d').strftime('%m-%d-%Y')
        #     opendate_input = driver.find_element(By.CSS_SELECTOR, "input#opendate")
        #     opendate_input.send_keys(formatted_date)
        #     time.sleep(1)
        #     input_date2= "2023-11-28"
        #     formatted_date = datetime.strptime(input_date2, '%Y-%m-%d').strftime('%m-%d-%Y')
        #     deaddate_input = driver.find_element(By.CSS_SELECTOR, "input#appdeadline")
        #     deaddate_input.send_keys(formatted_date)
        #     time.sleep(1)
        #     seats_available_input = driver.find_element(By.CSS_SELECTOR, "input#seats_available")
        #     seats_available_input.send_keys("20")
        #     time.sleep(1)
        #     file_path = 'C:\\Users\\Rony\\Downloads\\IT.jpeg'
        #     thumbnail_image_input = driver.find_element(By.CSS_SELECTOR, "input#thumbnail_image[type='file']")
        #     thumbnail_image_input.send_keys(file_path)
        #     time.sleep(3)
        #     submit_button = driver.find_element(By.CSS_SELECTOR, "input#submitBtn[type='submit']")
        #     submit_button.click()
        #     time.sleep(5)
        #     print("Added course successfully")
        #     manage = driver.find_element(By.CSS_SELECTOR, "a[href='/courselisting/'] button.btn.btn-primary.mt-3")
        #     manage.click()
        #     time.sleep(3)
        #     # Scroll down
        #     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        #     time.sleep(3)  # Optional sleep to let the page load

        #     # Scroll up (negative scroll distance)
        #     driver.execute_script("window.scrollTo(0, -document.body.scrollHeight);")
        #     time.sleep(5)  # Optional sleep after scrolling up
            
        #     home = driver.find_element(By.CSS_SELECTOR, "a.nav-link[href='/institute-dashboard/']")
        #     home.click()