# Generated by Django 4.2.6 on 2023-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_12th', models.FloatField()),
                ('GRE_Score', models.FloatField()),
                ('TOEFL_Score', models.FloatField()),
                ('CGPA', models.FloatField()),
                ('probability', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
            ],
        ),
    ]
