# Generated by Django 4.2.4 on 2023-10-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_course_application_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='ABC1234', max_length=20),
        ),
    ]
