# Generated by Django 4.2.4 on 2024-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_customuser_country_code_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_landlord',
            field=models.BooleanField(default=False, null=True, verbose_name='is_landlord'),
        ),
    ]
