# Generated by Django 4.2.4 on 2024-01-24 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_customuser_is_landlord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('property_location_link', models.URLField()),
                ('country', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('frontview_image', models.ImageField(upload_to='property_images/')),
                ('living_room_image', models.ImageField(upload_to='property_images/')),
                ('bedroom_image', models.ImageField(upload_to='property_images/')),
                ('bathroom_image', models.ImageField(upload_to='property_images/')),
                ('kitchen_image', models.ImageField(upload_to='property_images/')),
                ('dining_room_image', models.ImageField(upload_to='property_images/')),
                ('other1_image', models.ImageField(upload_to='property_images/')),
                ('other2_image', models.ImageField(upload_to='property_images/')),
                ('contact_number', models.CharField(max_length=15)),
                ('rent_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_duration_of_rent', models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 months'), (6, '6 months')])),
                ('number_of_bedrooms', models.IntegerField(choices=[(1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4 BHK')])),
                ('parking_area', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('heater', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
