# Generated by Django 4.2.4 on 2024-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
