# Generated by Django 4.2.4 on 2024-02-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_property_number_of_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
