# Generated by Django 4.2.4 on 2024-03-03 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_accbooking_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='accbooking',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accbooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
